In [1]:
#Data load


import pandas as pd

df = pd.read_excel("sales_raw_500.xlsx")

AttributeError: module 'pyarrow' has no attribute '__version__'

In [2]:
import os

print(os.getcwd())
print(os.listdir())

C:\Users\Admin\Desktop\Sales Data ETL & Business Intelligence Dashboard
['.ipynb_checkpoints', 'Cleaning.ipynb', 'sales_raw_500.xlsx', '~$sales_raw_500.xlsx']

In [3]:
import pandas as pd

df = pd.read_excel("sales_raw_500.xlsx")

df.head()

AttributeError: module 'pyarrow' has no attribute '__version__'

In [4]:
import os

print(os.getcwd())
print([f for f in os.listdir() if "pyarrow" in f.lower()])

C:\Users\Admin\Desktop\Sales Data ETL & Business Intelligence Dashboard
[]

In [1]:
import sys
print(sys.executable)

C:\Users\Admin\AppData\Local\Programs\Python\Python311\python.exe

In [1]:
print("Kernel restarted successfully")

Kernel restarted successfully

In [2]:
import pandas as pd

df = pd.read_excel("sales_raw_500.xlsx")

df.head()

   Order_ID Order_Date Customer Region  Product  Sales   Cost
0      1001 2023-01-13    Rohit  South   Mobile  23289  19118
1      1002 2023-10-07     Aman   West   Laptop   8905   5593
2      1003 2023-11-05    Rahul  South  Monitor  59987  39959
3      1004 2024-02-19    Rahul  South  Printer  49597  33892
4      1005 2024-01-26   Anjali  North   Laptop  54797  34468

In [3]:
df

     Order_ID Order_Date Customer Region  Product  Sales   Cost
0        1001 2023-01-13    Rohit  South   Mobile  23289  19118
1        1002 2023-10-07     Aman   West   Laptop   8905   5593
2        1003 2023-11-05    Rahul  South  Monitor  59987  39959
3        1004 2024-02-19    Rahul  South  Printer  49597  33892
4        1005 2024-01-26   Anjali  North   Laptop  54797  34468
..        ...        ...      ...    ...      ...    ...    ...
515      1389 2024-02-12    Vikas  North   Laptop  17924  12145
516      1496 2023-04-24    Kiran  North  Printer  23434  16388
517      1031 2023-02-19    Vikas   East  Printer  58883  43579
518      1317 2023-07-05     Aman  North   Laptop  76781  66865
519      1409 2024-01-16    Pooja  North  Monitor  19969  13586

[520 rows x 7 columns]

In [5]:
#duplicate remove


df = df.drop_duplicates()

In [6]:
df

     Order_ID Order_Date Customer Region  Product  Sales   Cost
0        1001 2023-01-13    Rohit  South   Mobile  23289  19118
1        1002 2023-10-07     Aman   West   Laptop   8905   5593
2        1003 2023-11-05    Rahul  South  Monitor  59987  39959
3        1004 2024-02-19    Rahul  South  Printer  49597  33892
4        1005 2024-01-26   Anjali  North   Laptop  54797  34468
..        ...        ...      ...    ...      ...    ...    ...
495      1496 2023-04-24    Kiran  North  Printer  23434  16388
496      1497 2023-06-27   Anjali  South   Laptop  49007  35970
497      1498 2023-05-08     Aman   East   Tablet  19160  15636
498      1499        NaT    Pooja   West   Mobile  59266  44326
499      1500 2023-10-07    Vikas  North  Printer  34567  22426

[500 rows x 7 columns]

In [11]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors='coerce')

C:\Users\Admin\AppData\Local\Temp\ipykernel_15200\356155431.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors='coerce')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order_ID    500 non-null    int64
 1   Order_Date  482 non-null    datetime64[ns]
 2   Customer    500 non-null    object
 3   Region      500 non-null    object
 4   Product     500 non-null    object
 5   Sales       500 non-null    int64
 6   Cost        500 non-null    int64
dtypes: datetime64[ns](1), int64(3), object(3)
memory usage: 31.2+ KB

In [13]:
df = df.dropna(subset=['Order_Date'])

In [14]:
df

     Order_ID Order_Date Customer Region  Product  Sales   Cost
0        1001 2023-01-13    Rohit  South   Mobile  23289  19118
1        1002 2023-10-07     Aman   West   Laptop   8905   5593
2        1003 2023-11-05    Rahul  South  Monitor  59987  39959
3        1004 2024-02-19    Rahul  South  Printer  49597  33892
4        1005 2024-01-26   Anjali  North   Laptop  54797  34468
..        ...        ...      ...    ...      ...    ...    ...
494      1495 2023-10-18    Rahul  South  Monitor  46709  40931
495      1496 2023-04-24    Kiran  North  Printer  23434  16388
496      1497 2023-06-27   Anjali  South   Laptop  49007  35970
497      1498 2023-05-08     Aman   East   Tablet  19160  15636
499      1500 2023-10-07    Vikas  North  Printer  34567  22426

[482 rows x 7 columns]

In [15]:
df['Profit'] = df['Sales']-df['Cost']
df['Year'] = df['Order_Date'].dt.year
df['Month'] = df['Order_Date'].dt.month

C:\Users\Admin\AppData\Local\Temp\ipykernel_15200\3679951826.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Profit'] = df['Sales']-df['Cost']
C:\Users\Admin\AppData\Local\Temp\ipykernel_15200\3679951826.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Year'] = df['Order_Date'].dt.year
C:\Users\Admin\AppData\Local\Temp\ipykernel_15200\3679951826.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Month'] = df['Order_Date'].dt.month

In [16]:
df = df.dropna(subset=['Order_Date'])

df = df.copy()

df['Profit'] = df['Sales'] - df['Cost']
df['Year'] = df['Order_Date'].dt.year
df['Month'] = df['Order_Date'].dt.month

In [17]:
df

,Order_ID,Order_Date,Customer,Region,Product,Sales,Cost,Profit,Year,Month
0,1001,2023-01-13,Rohit,South,Mobile,23289,19118,4171,2023,1
1,1002,2023-10-07,Aman,West,Laptop,8905,5593,3312,2023,10
2,1003,2023-11-05,Rahul,South,Monitor,59987,39959,20028,2023,11
3,1004,2024-02-19,Rahul,South,Printer,49597,33892,15705,2024,2
4,1005,2024-01-26,Anjali,North,Laptop,54797,34468,20329,2024,1
...,...,...,...,...,...,...,...,...,...,...
494,1495,2023-10-18,Rahul,South,Monitor,46709,40931,5778,2023,10
495,1496,2023-04-24,Kiran,North,Printer,23434,16388,7046,2023,4
496,1497,2023-06-27,Anjali,South,Laptop,49007,35970,13037,2023,6
497,1498,2023-05-08,Aman,East,Tablet,19160,15636,3524,2023,5
499,1500,2023-10-07,Vikas,North,Printer,34567,22426,12141,2023,10

In [18]:
df.to_csv('sales_cleaned.csv',index = False)

In [ ]:
#data python + Excel + SQL

In [ ]:
import pandas as pd
fromsqlalchemy import create_engine

In [ ]:
pd.read_csv('sales_cleaned.csv')

In [19]:
df

,Order_ID,Order_Date,Customer,Region,Product,Sales,Cost,Profit,Year,Month
0,1001,2023-01-13,Rohit,South,Mobile,23289,19118,4171,2023,1
1,1002,2023-10-07,Aman,West,Laptop,8905,5593,3312,2023,10
2,1003,2023-11-05,Rahul,South,Monitor,59987,39959,20028,2023,11
3,1004,2024-02-19,Rahul,South,Printer,49597,33892,15705,2024,2
4,1005,2024-01-26,Anjali,North,Laptop,54797,34468,20329,2024,1
...,...,...,...,...,...,...,...,...,...,...
494,1495,2023-10-18,Rahul,South,Monitor,46709,40931,5778,2023,10
495,1496,2023-04-24,Kiran,North,Printer,23434,16388,7046,2023,4
496,1497,2023-06-27,Anjali,South,Laptop,49007,35970,13037,2023,6
497,1498,2023-05-08,Aman,East,Tablet,19160,15636,3524,2023,5
499,1500,2023-10-07,Vikas,North,Printer,34567,22426,12141,2023,10

In [ ]:
engine = create_engine('mysql+pymysql://root:123456@localhost:3306/salesdb')

In [22]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:MyPassword123@localhost:5432/salesdb"
)

In [20]:
engine.connect()

NameError: name 'engine' is not defined

In [23]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:MyPassword123@localhost:5432/salesdb"
)

In [24]:
engine.connect()

In [25]:
df.head()

,Order_ID,Order_Date,Customer,Region,Product,Sales,Cost,Profit,Year,Month
0,1001,2023-01-13,Rohit,South,Mobile,23289,19118,4171,2023,1
1,1002,2023-10-07,Aman,West,Laptop,8905,5593,3312,2023,10
2,1003,2023-11-05,Rahul,South,Monitor,59987,39959,20028,2023,11
3,1004,2024-02-19,Rahul,South,Printer,49597,33892,15705,2024,2
4,1005,2024-01-26,Anjali,North,Laptop,54797,34468,20329,2024,1

In [26]:
df.to_sql(
    "sales",
    engine,
    if_exists="replace",
    index=False
)

482

In [1]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:Diksha2573@localhost:5432/salesdb"
)

In [2]:
engine.connect()

In [3]:
pd.read_sql("SELECT * FROM sales LIMIT 5;", engine)

NameError: name 'pd' is not defined

In [4]:
import pandas as pd

In [5]:
engine

Engine(postgresql+psycopg2://postgres:***@localhost:5432/salesdb)

In [9]:
df['Order_Date'] = pd.to_datetime(['Order_Date']), errors='coerce')

SyntaxError: unmatched ')' (1490730198.py, line 1)

In [6]:
import pandas as pd

In [7]:
pd.read_sql("SELECT * FROM sales LIMIT 5;", engine)

,Order_ID,Order_Date,Customer,Region,Product,Sales,Cost,Profit,Year,Month
0,1001,2023-01-13,Rohit,South,Mobile,23289,19118,4171,2023,1
1,1002,2023-10-07,Aman,West,Laptop,8905,5593,3312,2023,10
2,1003,2023-11-05,Rahul,South,Monitor,59987,39959,20028,2023,11
3,1004,2024-02-19,Rahul,South,Printer,49597,33892,15705,2024,2
4,1005,2024-01-26,Anjali,North,Laptop,54797,34468,20329,2024,1

In [9]:
df.to_sql(
    "sales",
    engine,
    if_exists="replace",
    index=False
)

NameError: name 'df' is not defined